# Generated by Django 4.2.6 on 2023-10-29 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название кнопки')),
                ('data', models.JSONField(blank=True, help_text='JSON-данные кнопки, включая текст и стили', null=True, verbose_name='Данные кнопки')),
            ],
            options={
                'verbose_name': 'Кнопку',
                'verbose_name_plural': 'Кнопки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ButtonPress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество нажатий')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button_presses', to='mailing.button', verbose_name='Кнопка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='button_presses', to='mailing.profile', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название рассылки')),
                ('text', models.TextField(verbose_name='текст рассылки')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата отправки')),
                ('buttons', models.ManyToManyField(related_name='buttons', to='mailing.button', verbose_name='кнопки для ответа на рассылку')),
                ('recipients', models.ManyToManyField(related_name='recipients', to='mailing.profile', verbose_name='получатели')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['-id'],
            },
        ),
    ]
