# Generated by Django 4.2.6 on 2023-11-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_button_buttonpress_broadcastmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcastmessage',
            options={'ordering': ['-id'], 'verbose_name': 'Отправленная Рассылка', 'verbose_name_plural': 'Отправленные Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='button',
            options={'ordering': ['-id'], 'verbose_name': 'Кнопка', 'verbose_name_plural': 'Кнопки'},
        ),
        migrations.AlterModelOptions(
            name='buttonpress',
            options={'ordering': ['-id'], 'verbose_name': 'Статистика по кликами', 'verbose_name_plural': 'Статистика по кликами'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='button',
            name='data',
            field=models.JSONField(blank=True, help_text='JSON-данные кнопки, включая текст и стили', null=True, verbose_name='JSON-данные кнопки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID пользователя в телеграмм'),
        ),
    ]
