# Generated by Django 4.2.6 on 2023-11-04 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_broadcastmessage_buttons_templatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonpress',
            name='broadcast_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button_presses', to='mailing.broadcastmessage', verbose_name='Рассылка'),
        ),
    ]
