# Generated by Django 4.2.6 on 2023-11-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_buttonpress_broadcast_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='button_layout',
            field=models.IntegerField(blank=True, null=True, verbose_name='Расположение кнопок'),
        ),
    ]
