# Generated by Django 4.2.6 on 2023-11-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_broadcastmessage_button_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='button_layout',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Расположение кнопок'),
        ),
    ]
