# Generated by Django 4.2.6 on 2023-11-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_broadcastmessage_button_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='row_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='номер строки'),
        ),
        migrations.AlterField(
            model_name='broadcastmessage',
            name='button_layout',
            field=models.IntegerField(blank=True, null=True, verbose_name='Расположение кнопок'),
        ),
    ]
