# Generated by Django 4.2.6 on 2023-11-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_alter_templatemessage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemessage',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название шаблона'),
        ),
        migrations.AlterField(
            model_name='templatemessage',
            name='text',
            field=models.TextField(verbose_name='текст шаблона'),
        ),
        migrations.AlterUniqueTogether(
            name='templatemessage',
            unique_together={('name', 'text')},
        ),
    ]
