# Generated by Django 4.2.6 on 2023-11-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_alter_templatemessage_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templatemessage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='templatemessage',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='название шаблона'),
        ),
    ]
