# Generated by Django 4.2.6 on 2023-11-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_alter_templatemessage_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemessage',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название шаблона'),
        ),
        migrations.AlterUniqueTogether(
            name='templatemessage',
            unique_together={('name', 'text')},
        ),
    ]
