# Generated by Django 4.2.6 on 2023-12-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0014_alter_templatemessage_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastmessage',
            name='button_layout',
        ),
        migrations.RemoveField(
            model_name='button',
            name='data',
        ),
    ]
